### ISSUE TITLE
feed_dict

### ISSUE THREAD

**Issue by danlutan** [lc222/attention-over-attention-tf-QA#1]
原始的代码feed_dict是存在错误的，测试的时候仍然会在训练集上，请问这个问题修改了吗？

**Comment by lc222** [comment]
测试的时候，index不是传入的2吗？？意思就是读取测试集数据吧，回头我试一下~

**Comment by lc222** [comment]
刚才跑了一下，测试的时候你需要把参数‘training’改成False，然后根据我的测试结果显示训练一般需要12秒左右，而测试的时候只需要6秒，所以应该是交换了数据的
