### ISSUE TITLE
请问一下哪块代码是第二层attention的？

### ISSUE THREAD

**Issue by guotong1988** [lc222/attention-over-attention-tf-QA#4]
一层attention和二层attention都在哪？分不清啊
谢谢！！
@lc222

**Comment by lc222** [comment]
我觉得你最好先好好看看论文把她的流程看明白。代码里面attention部分一共就不到10行代码，你行一行对应也能看明白的

**Comment by guotong1988** [comment]
谢谢！
我怎么感觉就是一层attention啊，我看了论文分不清啊。。

**Comment by guotong1988** [comment]
这句可以算是第一层attention吗
` M = tf.matmul(h_doc, h_query, adjoint_b=True)`
https://github.com/lc222/attention-over-attention-tf-QA/blob/master/model.py#L96
谢谢！

**Comment by lc222** [comment]
对，他和他下面一行。我觉得不要去纠结于两层的Attention，看论文里其实是现求一个矩阵，然后再经过一个行列变换，也就是两层Attention。这样去看代码应该会清楚一些
